# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addOne <- function(x) {
    invisible(.Call(`_introRcppMore_addOne`, x))
}

arrays <- function() {
    invisible(.Call(`_introRcppMore_arrays`))
}

countZeroes <- function(x) {
    .Call(`_introRcppMore_countZeroes`, x)
}

exampleD2 <- function() {
    invisible(.Call(`_introRcppMore_exampleD2`))
}

demonstrateSwap3 <- function(a, b) {
    invisible(.Call(`_introRcppMore_demonstrateSwap3`, a, b))
}

derivSquare <- function(x) {
    invisible(.Call(`_introRcppMore_derivSquare`, x))
}

intLog2 <- function(a) {
    .Call(`_introRcppMore_intLog2`, a)
}

exampleTemplate <- function() {
    invisible(.Call(`_introRcppMore_exampleTemplate`))
}

exempleTemplate2 <- function(x, y) {
    .Call(`_introRcppMore_exempleTemplate2`, x, y)
}

incrementAlpha <- function(x) {
    invisible(.Call(`_introRcppMore_incrementAlpha`, x))
}

pointers <- function() {
    invisible(.Call(`_introRcppMore_pointers`))
}

demoQuadratic <- function(a, b, c) {
    invisible(.Call(`_introRcppMore_demoQuadratic`, a, b, c))
}

references <- function() {
    invisible(.Call(`_introRcppMore_references`))
}

specials <- function() {
    .Call(`_introRcppMore_specials`)
}

demonstrateSwap <- function(a, b) {
    invisible(.Call(`_introRcppMore_demonstrateSwap`, a, b))
}

demonstrateSwap2 <- function(a, b) {
    invisible(.Call(`_introRcppMore_demonstrateSwap2`, a, b))
}

tests <- function(x) {
    invisible(.Call(`_introRcppMore_tests`, x))
}

twice <- function(x) {
    .Call(`_introRcppMore_twice`, x)
}

twice2 <- function(x) {
    .Call(`_introRcppMore_twice2`, x)
}

twice3 <- function(x) {
    .Call(`_introRcppMore_twice3`, x)
}

